version: '3'
services:
  master:
    image: mwernerds/sparkdemo
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    volumes:
      - .:/data
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      BRICKLANE_CFG_PATH: /code/config
      PYSPARK_PYTHON: python3.4
      PYTHONHASHSEED: 0
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager

  worker:
    image: mwernerds/sparkdemo
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_CONF_DIR: /conf
      BRICKLANE_CFG_PATH: /code/config
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      PYSPARK_PYTHON: python3.4
      PYTHONHASHSEED: 0
    links:
      - master
    ports:
      - 8081:8081
#    deploy:
#      mode: global
#      placement:
#       constraints:
#        - node.role != manager


